name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Build project
      run: dotnet build src/GeSoftDev/QueryFilter --configuration Release

    - name: Pack NuGet package
      run: dotnet pack src/GeSoftDev/QueryFilter --configuration Release

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push src/GeSoftDev/QueryFilter/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
